---
- name: Install LVM software
  yum: name=lvm2

- name: Create Volume Group
  lvg: vg={{ postgresql_lvm_vgname }} pvs={{ postgresql_lvm_pvs }} pesize={{ postgresql_lvm_pesize }} force=yes
  ignore_errors: yes

- name: Create Logical Volume
  lvol: vg={{ postgresql_lvm_vgname }} lv={{ postgresql_lvm_lvname }} size={{ postgresql_lvm_lvsize }}  force=false shrink=false

- name: Create Filesystems
  filesystem: fstype=xfs dev=/dev/{{ postgresql_lvm_vgname }}/{{ postgresql_lvm_lvname }}

- name: Configure Filesystem
  mount: state=mounted fstype=xfs src=/dev/{{ postgresql_lvm_vgname }}/{{ postgresql_lvm_lvname }} name={{ postgresql_lvm_fs }} opts=noatime

- name: Configure perms Filesystems
  file: state=directory mode=750 path={{ postgresql_lvm_fs }} owner={{ postgresql_admin_user }}

